name: pccmobile
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  mapbox_maps_flutter: ^2.1.0
  flutter_dotenv: ^6.0.0
 
  cupertino_icons: ^1.0.8

  geolocator: ^10.1.0

  url_launcher: ^6.3.2
  huawei_location: ^6.11.0+300
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/branches.json
    - assets/marker.png
    - .env
    - assets/PCCSUS.png
