// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrZ5e71DXDv_7GfbapR5LwWAHgUa7x-I',
    appId: '1:583119131925:web:dc9cc4738d000c391f851c',
    messagingSenderId: '583119131925',
    projectId: 'pcclocator',
    authDomain: 'pcclocator.firebaseapp.com',
    storageBucket: 'pcclocator.firebasestorage.app',
    measurementId: 'G-1LSHQQVB6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGsHbbwv_nLbwMyOgYNm03cMQEzrI6pdA',
    appId: '1:583119131925:android:43770d518513fce21f851c',
    messagingSenderId: '583119131925',
    projectId: 'pcclocator',
    storageBucket: 'pcclocator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDry6MvwZGorDk6FWdVoN9oe6Jgmk0dxI4',
    appId: '1:583119131925:ios:1efab883cc2c6dd21f851c',
    messagingSenderId: '583119131925',
    projectId: 'pcclocator',
    storageBucket: 'pcclocator.firebasestorage.app',
    iosBundleId: 'com.example.pccmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDry6MvwZGorDk6FWdVoN9oe6Jgmk0dxI4',
    appId: '1:583119131925:ios:1efab883cc2c6dd21f851c',
    messagingSenderId: '583119131925',
    projectId: 'pcclocator',
    storageBucket: 'pcclocator.firebasestorage.app',
    iosBundleId: 'com.example.pccmobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWrZ5e71DXDv_7GfbapR5LwWAHgUa7x-I',
    appId: '1:583119131925:web:ea6c31a24cc5b7371f851c',
    messagingSenderId: '583119131925',
    projectId: 'pcclocator',
    authDomain: 'pcclocator.firebaseapp.com',
    storageBucket: 'pcclocator.firebasestorage.app',
    measurementId: 'G-MZ4LXTHNLR',
  );
}
